# -*- coding: utf-8 -*-
"""UI.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ic0SkWzTKobiN_yeqpk-y7W2mGD5XSqH
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ui.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# from openai import AzureOpenAI
# 
# # ── Azure client (reads from Streamlit Cloud secrets) ─────────────────────────
# client = AzureOpenAI(
#     azure_endpoint=st.secrets["AZURE_OPENAI_ENDPOINT"],
#     api_key=st.secrets["AZURE_OPENAI_API_KEY"],
#     api_version=st.secrets.get("AZURE_OPENAI_API_VERSION", "2024-02-01"),
# )
# DEPLOYMENT = st.secrets.get("AZURE_OPENAI_DEPLOYMENT", "gpt-4o")
# 
# RESEARCH_CONTEXT = """
# You are an AI clinical decision-support agent built on the research:
# 'Predictive Modeling: Utilizing Machine Learning to Forecast Diabetes Hospital Re-admissions'
# by Temitope Adereni, DataraFlow DF2025-036.
# 
# KEY FINDINGS:
# - Dataset: UCI Diabetes 130-US Hospitals 1999-2008 (100,000+ encounters)
# - Logistic Regression AUC = 0.624 outperforms Random Forest AUC = 0.609 (H1 not supported)
# - External validation: LR AUC = 0.644 | RF AUC = 0.605
# - Utilisation features improved AUC from 0.529 to 0.629 (H2 SUPPORTED)
# - SMOTE did NOT improve UCI performance (H3 MIXED)
# - Top predictors: number_inpatient, time_in_hospital, number_emergency, number_outpatient
# """
# 
# def ask_agent(system_prompt, user_prompt, max_tokens=400):
#     try:
#         resp = client.chat.completions.create(
#             model=DEPLOYMENT,
#             messages=[
#                 {"role": "system", "content": RESEARCH_CONTEXT + "\n\n" + system_prompt},
#                 {"role": "user",   "content": user_prompt},
#             ],
#             max_tokens=max_tokens,
#             temperature=0.4,
#         )
#         return resp.choices[0].message.content
#     except Exception as e:
#         return f"⚠️ Azure OpenAI error: {e}"
# 
# def compute_risk(inpatient, los, emergency, outpatient, diagnoses, medications, hba1c):
#     score = (
#         inpatient   * 0.35 +
#         los         * 0.25 +
#         emergency   * 0.20 +
#         outpatient  * 0.10 +
#         diagnoses   * 0.07 +
#         medications * 0.03
#     )
#     if hba1c in [">7", ">8"]:
#         score *= 1.15
#     pct = min(int((score / 14) * 100), 96)
#     if pct >= 60:
#         level, colour, emoji = "High",     "#e74c3c", "🔴"
#     elif pct >= 35:
#         level, colour, emoji = "Moderate", "#f39c12", "🟡"
#     else:
#         level, colour, emoji = "Low",      "#27ae60", "🟢"
#     return pct, level, colour, emoji
# 
# # ── Page config ───────────────────────────────────────────────────────────────
# st.set_page_config(
#     page_title="DiabetesGuard AI",
#     page_icon="🏥",
#     layout="wide",
#     initial_sidebar_state="expanded",
# )
# 
# st.markdown("""
# <style>
#     .agent-box {
#         background: #eaf4fb; border-radius: 10px;
#         padding: 16px; margin-bottom: 12px;
#         border-left: 4px solid #2980b9;
#     }
#     .section-title { font-size: 1.1rem; font-weight: 600; margin-bottom: 6px; }
# </style>
# """, unsafe_allow_html=True)
# 
# # ── Sidebar ───────────────────────────────────────────────────────────────────
# with st.sidebar:
#     st.markdown("## 🏥 DiabetesGuard AI")
#     st.caption("Multi-Agent Triage Dashboard")
#     st.markdown("---")
#     page = st.radio("", [
#         "🏠  Home",
#         "🔬  Patient Triage",
#         "📊  Model Results",
#         "📈  Feature Analysis",
#         "🤖  Research Assistant",
#     ], label_visibility="collapsed")
#     st.markdown("---")
#     st.markdown("**Author:** Temitope Adereni")
#     st.markdown("**Programme:** DataraFlow DF2025-036")
#     st.markdown("**Dataset:** UCI Diabetes 130-US Hospitals")
#     st.markdown("**Model:** Logistic Regression (AUC 0.624)")
#     st.markdown("---")
#     st.markdown("**🤖 Active Agents**")
#     st.markdown("• 🔴 RiskAssessor\n• 🔵 ExplainerAgent\n• 🟢 DischargeAdvisor\n• 🟣 ResearchAssistant")
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # HOME
# # ══════════════════════════════════════════════════════════════════════════════
# if page == "🏠  Home":
#     st.title("🏥 DiabetesGuard AI")
#     st.markdown("### Multi-Agent Patient Triage & Readmission Risk Dashboard")
#     st.markdown("""
#     > *Based on: **Predictive Modeling: Utilizing Machine Learning to Forecast
#     > Diabetes Hospital Re-admissions** — Temitope Adereni, DataraFlow DF2025-036*
# 
#     This system routes patient data through **3 specialised Azure OpenAI agents**
#     to triage readmission risk, explain predictions, and generate discharge plans.
#     """)
# 
#     c1, c2, c3, c4 = st.columns(4)
#     c1.metric("LR Model AUC",        "0.624", "Best performer")
#     c2.metric("RF Model AUC",        "0.609")
#     c3.metric("w/ Utilisation Features", "0.629", "+19% vs demo-only")
#     c4.metric("External Validation", "0.644", "Generalises well")
# 
#     st.markdown("---")
#     st.markdown("### 🔁 The 3-Agent Pipeline")
#     a1, arr1, a2, arr2, a3 = st.columns([2, 0.2, 2, 0.2, 2])
#     with a1:
#         st.info("**🔴 RiskAssessor**\n\nTakes patient inputs → outputs urgency: 🔴 High / 🟡 Moderate / 🟢 Low")
#     arr1.markdown("<div style='text-align:center;font-size:2rem;margin-top:35px'>→</div>", unsafe_allow_html=True)
#     with a2:
#         st.info("**🔵 ExplainerAgent**\n\nExplains *why* using your feature importance findings — XAI layer")
#     arr2.markdown("<div style='text-align:center;font-size:2rem;margin-top:35px'>→</div>", unsafe_allow_html=True)
#     with a3:
#         st.info("**🟢 DischargeAdvisor**\n\nGenerates personalised discharge plan to reduce readmission probability")
# 
#     st.markdown("---")
#     st.markdown("### 📋 Research Hypotheses")
#     hyp_df = pd.DataFrame({
#         "Hypothesis": ["H1: Random Forest > Logistic Regression",
#                        "H2: Utilisation features improve AUC",
#                        "H3: SMOTE improves Recall"],
#         "Result":     ["❌ Not supported — LR won (0.624 vs 0.609)",
#                        "✅ Supported — AUC 0.529 → 0.629",
#                        "⚠️ Mixed — helped externally, not on UCI"],
#         "Implication":["Use simpler interpretable models",
#                        "Always include prior visit counts & LOS",
#                        "Apply SMOTE cautiously per dataset"],
#     })
#     st.dataframe(hyp_df, use_container_width=True, hide_index=True)
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # PATIENT TRIAGE
# # ══════════════════════════════════════════════════════════════════════════════
# elif page == "🔬  Patient Triage":
#     st.title("🔬 Patient Triage")
#     st.markdown("Enter patient details. Three Azure OpenAI agents will assess risk, explain it, and suggest a discharge plan.")
# 
#     with st.form("triage_form"):
#         st.markdown("#### 👤 Demographics")
#         d1, d2, d3 = st.columns(3)
#         age    = d1.selectbox("Age Group", ["[0-10)","[10-20)","[20-30)","[30-40)","[40-50)",
#                                              "[50-60)","[60-70)","[70-80)","[80-90)","[90-100)"], index=6)
#         gender = d2.selectbox("Gender", ["Male", "Female"])
#         race   = d3.selectbox("Race", ["Caucasian","AfricanAmerican","Hispanic","Asian","Other"])
# 
#         st.markdown("#### 🏥 Utilisation Features *(strongest predictors)*")
#         u1, u2, u3, u4 = st.columns(4)
#         los        = u1.slider("Length of Stay (days)",   1, 14, 5)
#         inpatient  = u2.slider("Prior Inpatient Visits",  0, 15, 2)
#         outpatient = u3.slider("Prior Outpatient Visits", 0, 15, 1)
#         emergency  = u4.slider("Prior Emergency Visits",  0, 15, 1)
# 
#         st.markdown("#### 💊 Clinical Variables")
#         cl1, cl2, cl3, cl4 = st.columns(4)
#         medications = cl1.slider("Num. Medications", 1, 30, 12)
#         diagnoses   = cl2.slider("Num. Diagnoses",   1, 16,  7)
#         hba1c       = cl3.selectbox("HbA1c Result", ["None","Normal",">7",">8"])
#         insulin     = cl4.selectbox("Insulin", ["No","Steady","Up","Down"])
# 
#         submitted = st.form_submit_button("🚀 Run Multi-Agent Assessment", use_container_width=True)
# 
#     if submitted:
#         risk_pct, level, colour, emoji = compute_risk(
#             inpatient, los, emergency, outpatient, diagnoses, medications, hba1c
#         )
#         patient_summary = {
#             "age_group": age, "gender": gender, "race": race,
#             "time_in_hospital": los, "number_inpatient": inpatient,
#             "number_outpatient": outpatient, "number_emergency": emergency,
#             "num_medications": medications, "num_diagnoses": diagnoses,
#             "HbA1c_result": hba1c, "insulin": insulin,
#             "risk_pct": risk_pct, "risk_level": level,
#         }
# 
#         st.markdown("---")
#         col_gauge, col_agent1 = st.columns([1, 2])
# 
#         with col_gauge:
#             st.markdown("### Risk Score")
#             fig, ax = plt.subplots(figsize=(4, 2.4), subplot_kw=dict(aspect="equal"))
#             ax.pie([33, 33, 34], colors=["#27ae60","#f39c12","#e74c3c"],
#                    startangle=180, counterclock=False,
#                    wedgeprops=dict(width=0.45))
#             needle_rad = np.radians(180 - (risk_pct / 100 * 180))
#             ax.annotate("", xy=(0.38*np.cos(needle_rad), 0.38*np.sin(needle_rad)),
#                         xytext=(0, 0),
#                         arrowprops=dict(arrowstyle="->", color="black", lw=2.5))
#             ax.text(0, -0.28, f"{risk_pct}%",   ha="center", fontsize=22, fontweight="bold", color=colour)
#             ax.text(0, -0.55, f"{emoji} {level} Risk", ha="center", fontsize=11, color=colour)
#             ax.axis("off")
#             st.pyplot(fig, use_container_width=True)
#             plt.close()
#             st.progress(risk_pct / 100)
# 
#         with col_agent1:
#             st.markdown('<p class="section-title">🔴 RiskAssessor Agent</p>', unsafe_allow_html=True)
#             with st.spinner("Assessing readmission risk..."):
#                 a1_out = ask_agent(
#                     "You are the RiskAssessor agent. Give a 3-sentence clinical risk assessment. "
#                     "State risk level clearly, reference the patient's most concerning utilisation "
#                     "features, and relate to the model AUC of 0.624.",
#                     f"Assess 30-day readmission risk: {patient_summary}",
#                 )
#             st.markdown(f'<div class="agent-box">{a1_out}</div>', unsafe_allow_html=True)
# 
#         st.markdown('<p class="section-title">🔵 ExplainerAgent — Why is this patient at risk?</p>', unsafe_allow_html=True)
#         with st.spinner("Explaining risk drivers..."):
#             a2_out = ask_agent(
#                 "You are the ExplainerAgent. Explain in exactly 3 bullet points which features "
#                 "drive this patient's risk and why, referencing the research finding that "
#                 "utilisation features improved AUC from 0.529 to 0.629.",
#                 f"Explain risk drivers: {patient_summary}",
#             )
#         st.markdown(f'<div class="agent-box">{a2_out}</div>', unsafe_allow_html=True)
# 
#         st.markdown('<p class="section-title">🟢 DischargeAdvisor — Personalised Discharge Plan</p>', unsafe_allow_html=True)
#         with st.spinner("Generating discharge recommendations..."):
#             a3_out = ask_agent(
#                 "You are the DischargeAdvisor. Give 4 specific, empathetic discharge "
#                 "recommendations to reduce 30-day readmission. Tailor to the patient's "
#                 "age group, HbA1c, and utilisation history. Use plain language.",
#                 f"Create discharge plan: {patient_summary}. Risk: {level} ({risk_pct}%)",
#                 max_tokens=500,
#             )
#         st.success(a3_out)
# 
#         st.markdown("---")
#         report = f"""DiabetesGuard AI — Triage Report
# ===================================
# Risk Score : {risk_pct}% ({level})
# Age: {age} | Gender: {gender} | Race: {race}
# LOS: {los} days | Inpatient: {inpatient} | Emergency: {emergency}
# HbA1c: {hba1c} | Medications: {medications} | Diagnoses: {diagnoses}
# 
# RISK ASSESSMENT
# {a1_out}
# 
# EXPLANATION
# {a2_out}
# 
# DISCHARGE PLAN
# {a3_out}
# 
# Generated by DiabetesGuard AI | Temitope Adereni | DataraFlow DF2025-036
# """
#         st.download_button("📥 Download Report", report,
#                            file_name="triage_report.txt", mime="text/plain")
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # MODEL RESULTS
# # ══════════════════════════════════════════════════════════════════════════════
# elif page == "📊  Model Results":
#     st.title("📊 Model Performance Results")
# 
#     tab1, tab2, tab3 = st.tabs(["H1 — LR vs RF", "H2 — Feature Sets", "H3 — SMOTE"])
# 
#     with tab1:
#         df = pd.DataFrame({
#             "Model":   ["Logistic Regression","Random Forest","Logistic Regression","Random Forest"],
#             "Dataset": ["UCI","UCI","External","External"],
#             "AUC":     [0.624, 0.609, 0.644, 0.605],
#             "F1":      [0.028, 0.012, 0.484, 0.537],
#         })
#         st.dataframe(df, use_container_width=True, hide_index=True)
#         fig, ax = plt.subplots(figsize=(8, 4))
#         x, w = np.arange(2), 0.32
#         b1 = ax.bar(x-w/2, [0.624,0.609], w, label="UCI",      color="#3498db")
#         b2 = ax.bar(x+w/2, [0.644,0.605], w, label="External", color="#2ecc71")
#         ax.set_xticks(x); ax.set_xticklabels(["Logistic Regression","Random Forest"])
#         ax.set_ylim(0.55, 0.68); ax.set_ylabel("AUC")
#         ax.set_title("AUC: LR vs Random Forest across Datasets")
#         ax.legend(); ax.bar_label(b1, fmt="%.3f", padding=3); ax.bar_label(b2, fmt="%.3f", padding=3)
#         st.pyplot(fig); plt.close()
#         st.info("**H1:** LR consistently outperforms RF — simpler models generalise better on sparse clinical data.")
# 
#     with tab2:
#         df2 = pd.DataFrame({
#             "Feature Set": ["Demographics Only","Demographics + Utilisation"],
#             "ROC-AUC": [0.529, 0.629], "PR-AUC": [0.120, 0.189],
#             "Recall":  [0.765, 0.388], "F1":      [0.205, 0.243],
#         })
#         st.dataframe(df2, use_container_width=True, hide_index=True)
#         fig2, axes = plt.subplots(1, 3, figsize=(12, 4))
#         for i, (m, dv, uv) in enumerate(zip(
#             ["ROC-AUC","PR-AUC","F1"],
#             [0.529, 0.120, 0.205],
#             [0.629, 0.189, 0.243]
#         )):
#             bars = axes[i].bar(["Demo Only","Demo+Util"], [dv, uv], color=["#95a5a6","#3498db"])
#             axes[i].set_title(m); axes[i].set_ylim(0, max(dv,uv)*1.25)
#             axes[i].bar_label(bars, fmt="%.3f", padding=3)
#         plt.tight_layout(); st.pyplot(fig2); plt.close()
#         st.success("**H2 ✅:** Utilisation features boosted AUC by +19% (0.529 → 0.629).")
# 
#     with tab3:
#         df3 = pd.DataFrame({
#             "Model":  ["Baseline","SMOTE"],
#             "AUC":    [0.628, 0.606],
#             "Recall": [0.495, 0.423],
#         })
#         st.dataframe(df3, use_container_width=True, hide_index=True)
#         fig3, ax3 = plt.subplots(figsize=(6, 4))
#         x3 = np.arange(2)
#         b3 = ax3.bar(x3-0.2, [0.628,0.495], 0.35, label="Baseline", color="#3498db")
#         b4 = ax3.bar(x3+0.2, [0.606,0.423], 0.35, label="SMOTE",    color="#e74c3c")
#         ax3.set_xticks(x3); ax3.set_xticklabels(["AUC","Recall"])
#         ax3.set_ylim(0, 0.75); ax3.set_title("Baseline vs SMOTE — UCI Dataset")
#         ax3.legend(); ax3.bar_label(b3, fmt="%.3f", padding=3); ax3.bar_label(b4, fmt="%.3f", padding=3)
#         st.pyplot(fig3); plt.close()
#         st.warning("**H3 ⚠️ Mixed:** SMOTE reduced AUC and Recall on UCI — introduced noise.")
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # FEATURE ANALYSIS
# # ══════════════════════════════════════════════════════════════════════════════
# elif page == "📈  Feature Analysis":
#     st.title("📈 Feature Analysis")
# 
#     features   = ["number_inpatient","time_in_hospital","number_emergency",
#                   "number_outpatient","num_diagnoses","num_medications","age"]
#     importance = [0.35, 0.25, 0.20, 0.10, 0.05, 0.03, 0.02]
#     colours    = ["#e74c3c","#e67e22","#f39c12","#3498db","#2ecc71","#9b59b6","#95a5a6"]
# 
#     fig4, ax4 = plt.subplots(figsize=(9, 4))
#     bars = ax4.barh(features[::-1], importance[::-1], color=colours[::-1])
#     ax4.set_xlabel("Relative Importance")
#     ax4.set_title("Feature Importance — Logistic Regression (your research)")
#     ax4.bar_label(bars, fmt="%.2f", padding=3)
#     st.pyplot(fig4); plt.close()
# 
#     col_a, col_b = st.columns(2)
#     with col_a:
#         fig5, ax5 = plt.subplots(figsize=(5, 3))
#         ax5.barh(["Demo Only","Demo + Utilisation"], [0.529, 0.629], color=["#95a5a6","#3498db"])
#         ax5.set_xlim(0.45, 0.65); ax5.set_xlabel("AUC"); ax5.set_title("AUC by Feature Set (H2)")
#         for i, v in enumerate([0.529, 0.629]):
#             ax5.text(v+0.002, i, f"{v:.3f}", va="center", fontweight="bold")
#         st.pyplot(fig5); plt.close()
# 
#     with col_b:
#         fig6, ax6 = plt.subplots(figsize=(5, 3))
#         ax6.pie([53, 35, 12],
#                 labels=["No Readmission","Readmitted >30d","Readmitted <30d"],
#                 explode=(0,0,0.08), autopct="%1.0f%%",
#                 colors=["#2ecc71","#f39c12","#e74c3c"],
#                 startangle=90, textprops={"fontsize": 9})
#         ax6.set_title("UCI Dataset — Class Distribution")
#         st.pyplot(fig6); plt.close()
# 
#     st.info("Only ~11% of UCI patients are readmitted within 30 days — heavy class imbalance, which is why SMOTE was explored in H3.")
# 
# # ══════════════════════════════════════════════════════════════════════════════
# # RESEARCH ASSISTANT
# # ══════════════════════════════════════════════════════════════════════════════
# elif page == "🤖  Research Assistant":
#     st.title("🤖 Research Assistant")
#     st.markdown("Ask anything about your research. Powered by **Azure OpenAI GPT-4o**.")
# 
#     q1, q2, q3 = st.columns(3)
#     if q1.button("Why did LR beat Random Forest?"):
#         st.session_state.setdefault("messages", [])
#         st.session_state.messages.append({"role":"user","content":"Why did Logistic Regression outperform Random Forest?"})
#     if q2.button("Why did SMOTE fail on UCI?"):
#         st.session_state.setdefault("messages", [])
#         st.session_state.messages.append({"role":"user","content":"Why did SMOTE not improve performance on the UCI dataset?"})
#     if q3.button("How do I improve AUC further?"):
#         st.session_state.setdefault("messages", [])
#         st.session_state.messages.append({"role":"user","content":"What steps could I take to improve AUC beyond 0.624?"})
# 
#     st.markdown("---")
# 
#     if "messages" not in st.session_state:
#         st.session_state.messages = []
# 
#     for msg in st.session_state.messages:
#         with st.chat_message(msg["role"]):
#             st.markdown(msg["content"])
# 
#     if prompt := st.chat_input("Ask about your diabetes readmission research..."):
#         st.session_state.messages.append({"role":"user","content":prompt})
#         with st.chat_message("user"):
#             st.markdown(prompt)
#         with st.chat_message("assistant"):
#             with st.spinner("Thinking..."):
#                 try:
#                     resp = client.chat.completions.create(
#                         model=DEPLOYMENT,
#                         messages=(
#                             [{"role":"system","content": RESEARCH_CONTEXT +
#                               "\nAnswer clearly and reference real numbers from the research."}]
#                             + st.session_state.messages
#                         ),
#                         max_tokens=600,
#                     )
#                     reply = resp.choices[0].message.content
#                 except Exception as e:
#                     reply = f"⚠️ Azure OpenAI error: {e}"
#             st.markdown(reply)
#         st.session_state.messages.append({"role":"assistant","content":reply})
# 
#     if st.button("🗑️ Clear chat"):
#         st.session_state.messages = []
#         st.rerun()